# This is a config for E2B sandbox template.
# You can use template ID (x0ro39dgzqq1ef8vtnya) or template name (v0-clone-nextjs-app) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-clone-nextjs-app") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-clone-nextjs-app") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-clone-nextjs-app')

team_id = "5b4423ac-a880-4877-b1b9-2526a4141446"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-clone-nextjs-app"
template_id = "x0ro39dgzqq1ef8vtnya"
